/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 11
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_RBRACK = 1,
  anon_sym_EQ = 2,
  sym_line_break = 3,
  sym_l_bracket = 4,
  sym_int = 5,
  sym_float = 6,
  sym_quoted_string = 7,
  sym_unquoted_string = 8,
  sym_whitespace = 9,
  sym_comma = 10,
  sym_line_comment = 11,
  sym_section_name = 12,
  sym_key = 13,
  sym_program = 14,
  sym__line = 15,
  sym__line_content = 16,
  sym_section = 17,
  sym_comment = 18,
  sym_item = 19,
  sym_value_list = 20,
  aux_sym_program_repeat1 = 21,
  aux_sym_value_list_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [sym_line_break] = "line_break",
  [sym_l_bracket] = "l_bracket",
  [sym_int] = "int",
  [sym_float] = "float",
  [sym_quoted_string] = "quoted_string",
  [sym_unquoted_string] = "unquoted_string",
  [sym_whitespace] = "whitespace",
  [sym_comma] = "comma",
  [sym_line_comment] = "line_comment",
  [sym_section_name] = "section_name",
  [sym_key] = "key",
  [sym_program] = "program",
  [sym__line] = "_line",
  [sym__line_content] = "_line_content",
  [sym_section] = "section",
  [sym_comment] = "comment",
  [sym_item] = "item",
  [sym_value_list] = "value_list",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_value_list_repeat1] = "value_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_line_break] = sym_line_break,
  [sym_l_bracket] = sym_l_bracket,
  [sym_int] = sym_int,
  [sym_float] = sym_float,
  [sym_quoted_string] = sym_quoted_string,
  [sym_unquoted_string] = sym_unquoted_string,
  [sym_whitespace] = sym_whitespace,
  [sym_comma] = sym_comma,
  [sym_line_comment] = sym_line_comment,
  [sym_section_name] = sym_section_name,
  [sym_key] = sym_key,
  [sym_program] = sym_program,
  [sym__line] = sym__line,
  [sym__line_content] = sym__line_content,
  [sym_section] = sym_section,
  [sym_comment] = sym_comment,
  [sym_item] = sym_item,
  [sym_value_list] = sym_value_list,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_value_list_repeat1] = aux_sym_value_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_line_break] = {
    .visible = true,
    .named = true,
  },
  [sym_l_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_comma] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__line_content] = {
    .visible = false,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_value_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '=') ADVANCE(3);
      if (lookahead == ']') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 0, .external_lex_state = 5},
  [12] = {.lex_state = 0, .external_lex_state = 4},
  [13] = {.lex_state = 0, .external_lex_state = 4},
  [14] = {.lex_state = 0, .external_lex_state = 4},
  [15] = {.lex_state = 0, .external_lex_state = 4},
  [16] = {.lex_state = 0, .external_lex_state = 4},
  [17] = {.lex_state = 0, .external_lex_state = 4},
  [18] = {.lex_state = 0, .external_lex_state = 4},
  [19] = {.lex_state = 0, .external_lex_state = 4},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0, .external_lex_state = 6},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0, .external_lex_state = 6},
  [24] = {.lex_state = 0, .external_lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_line_break] = ACTIONS(1),
    [sym_l_bracket] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_unquoted_string] = ACTIONS(1),
    [sym_whitespace] = ACTIONS(1),
    [sym_comma] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [sym_section_name] = ACTIONS(1),
    [sym_key] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(22),
    [sym__line] = STATE(2),
    [sym__line_content] = STATE(13),
    [sym_section] = STATE(13),
    [sym_comment] = STATE(13),
    [sym_item] = STATE(13),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(5),
    [sym_line_break] = ACTIONS(7),
    [sym_l_bracket] = ACTIONS(9),
    [sym_whitespace] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(13),
    [sym_key] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym__line_content] = STATE(17),
    [sym_section] = STATE(17),
    [sym_comment] = STATE(17),
    [sym_item] = STATE(17),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_EQ] = ACTIONS(5),
    [sym_line_break] = ACTIONS(19),
    [sym_l_bracket] = ACTIONS(9),
    [sym_whitespace] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(13),
    [sym_key] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym__line_content] = STATE(24),
    [sym_section] = STATE(24),
    [sym_comment] = STATE(24),
    [sym_item] = STATE(24),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(23),
    [sym_line_break] = ACTIONS(26),
    [sym_l_bracket] = ACTIONS(29),
    [sym_whitespace] = ACTIONS(32),
    [sym_line_comment] = ACTIONS(35),
    [sym_key] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    STATE(6), 1,
      aux_sym_value_list_repeat1,
    STATE(14), 1,
      sym_value_list,
    ACTIONS(41), 2,
      sym_line_break,
      ts_builtin_sym_end,
    ACTIONS(43), 7,
      sym_int,
      sym_float,
      sym_quoted_string,
      sym_unquoted_string,
      sym_whitespace,
      sym_comma,
      sym_line_comment,
  [20] = 4,
    STATE(6), 1,
      aux_sym_value_list_repeat1,
    STATE(18), 1,
      sym_value_list,
    ACTIONS(45), 2,
      sym_line_break,
      ts_builtin_sym_end,
    ACTIONS(43), 7,
      sym_int,
      sym_float,
      sym_quoted_string,
      sym_unquoted_string,
      sym_whitespace,
      sym_comma,
      sym_line_comment,
  [40] = 3,
    STATE(7), 1,
      aux_sym_value_list_repeat1,
    ACTIONS(47), 2,
      sym_line_break,
      ts_builtin_sym_end,
    ACTIONS(49), 7,
      sym_int,
      sym_float,
      sym_quoted_string,
      sym_unquoted_string,
      sym_whitespace,
      sym_comma,
      sym_line_comment,
  [57] = 3,
    STATE(7), 1,
      aux_sym_value_list_repeat1,
    ACTIONS(51), 2,
      sym_line_break,
      ts_builtin_sym_end,
    ACTIONS(53), 7,
      sym_int,
      sym_float,
      sym_quoted_string,
      sym_unquoted_string,
      sym_whitespace,
      sym_comma,
      sym_line_comment,
  [74] = 1,
    ACTIONS(56), 7,
      sym_line_break,
      sym_l_bracket,
      sym_whitespace,
      sym_line_comment,
      sym_key,
      ts_builtin_sym_end,
      anon_sym_EQ,
  [84] = 2,
    ACTIONS(60), 1,
      anon_sym_RBRACK,
    ACTIONS(58), 2,
      sym_line_break,
      ts_builtin_sym_end,
  [92] = 2,
    ACTIONS(64), 1,
      anon_sym_RBRACK,
    ACTIONS(62), 2,
      sym_line_break,
      ts_builtin_sym_end,
  [100] = 2,
    ACTIONS(66), 1,
      sym_l_bracket,
    ACTIONS(68), 1,
      sym_line_comment,
  [107] = 1,
    ACTIONS(70), 2,
      sym_line_break,
      ts_builtin_sym_end,
  [112] = 2,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 1,
      sym_line_break,
  [119] = 1,
    ACTIONS(45), 2,
      sym_line_break,
      ts_builtin_sym_end,
  [124] = 1,
    ACTIONS(74), 2,
      sym_line_break,
      ts_builtin_sym_end,
  [129] = 1,
    ACTIONS(62), 2,
      sym_line_break,
      ts_builtin_sym_end,
  [134] = 2,
    ACTIONS(72), 1,
      sym_line_break,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
  [141] = 1,
    ACTIONS(78), 2,
      sym_line_break,
      ts_builtin_sym_end,
  [146] = 1,
    ACTIONS(80), 2,
      sym_line_break,
      ts_builtin_sym_end,
  [151] = 1,
    ACTIONS(82), 1,
      anon_sym_EQ,
  [155] = 1,
    ACTIONS(84), 1,
      sym_section_name,
  [159] = 1,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
  [163] = 1,
    ACTIONS(88), 1,
      sym_section_name,
  [167] = 1,
    ACTIONS(72), 1,
      sym_line_break,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 20,
  [SMALL_STATE(6)] = 40,
  [SMALL_STATE(7)] = 57,
  [SMALL_STATE(8)] = 74,
  [SMALL_STATE(9)] = 84,
  [SMALL_STATE(10)] = 92,
  [SMALL_STATE(11)] = 100,
  [SMALL_STATE(12)] = 107,
  [SMALL_STATE(13)] = 112,
  [SMALL_STATE(14)] = 119,
  [SMALL_STATE(15)] = 124,
  [SMALL_STATE(16)] = 129,
  [SMALL_STATE(17)] = 134,
  [SMALL_STATE(18)] = 141,
  [SMALL_STATE(19)] = 146,
  [SMALL_STATE(20)] = 151,
  [SMALL_STATE(21)] = 155,
  [SMALL_STATE(22)] = 159,
  [SMALL_STATE(23)] = 163,
  [SMALL_STATE(24)] = 167,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [86] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_line_break = 0,
  ts_external_token_l_bracket = 1,
  ts_external_token_int = 2,
  ts_external_token_float = 3,
  ts_external_token_quoted_string = 4,
  ts_external_token_unquoted_string = 5,
  ts_external_token_whitespace = 6,
  ts_external_token_comma = 7,
  ts_external_token_line_comment = 8,
  ts_external_token_section_name = 9,
  ts_external_token_key = 10,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_line_break] = sym_line_break,
  [ts_external_token_l_bracket] = sym_l_bracket,
  [ts_external_token_int] = sym_int,
  [ts_external_token_float] = sym_float,
  [ts_external_token_quoted_string] = sym_quoted_string,
  [ts_external_token_unquoted_string] = sym_unquoted_string,
  [ts_external_token_whitespace] = sym_whitespace,
  [ts_external_token_comma] = sym_comma,
  [ts_external_token_line_comment] = sym_line_comment,
  [ts_external_token_section_name] = sym_section_name,
  [ts_external_token_key] = sym_key,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_line_break] = true,
    [ts_external_token_l_bracket] = true,
    [ts_external_token_int] = true,
    [ts_external_token_float] = true,
    [ts_external_token_quoted_string] = true,
    [ts_external_token_unquoted_string] = true,
    [ts_external_token_whitespace] = true,
    [ts_external_token_comma] = true,
    [ts_external_token_line_comment] = true,
    [ts_external_token_section_name] = true,
    [ts_external_token_key] = true,
  },
  [2] = {
    [ts_external_token_line_break] = true,
    [ts_external_token_l_bracket] = true,
    [ts_external_token_whitespace] = true,
    [ts_external_token_line_comment] = true,
    [ts_external_token_key] = true,
  },
  [3] = {
    [ts_external_token_line_break] = true,
    [ts_external_token_int] = true,
    [ts_external_token_float] = true,
    [ts_external_token_quoted_string] = true,
    [ts_external_token_unquoted_string] = true,
    [ts_external_token_whitespace] = true,
    [ts_external_token_comma] = true,
    [ts_external_token_line_comment] = true,
  },
  [4] = {
    [ts_external_token_line_break] = true,
  },
  [5] = {
    [ts_external_token_l_bracket] = true,
    [ts_external_token_line_comment] = true,
  },
  [6] = {
    [ts_external_token_section_name] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_bni_external_scanner_create(void);
void tree_sitter_bni_external_scanner_destroy(void *);
bool tree_sitter_bni_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_bni_external_scanner_serialize(void *, char *);
void tree_sitter_bni_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bni(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_bni_external_scanner_create,
      tree_sitter_bni_external_scanner_destroy,
      tree_sitter_bni_external_scanner_scan,
      tree_sitter_bni_external_scanner_serialize,
      tree_sitter_bni_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "bni",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
